export const mockSchedules = [
  {
    id: '1',
    teacherUid: 'demo-teacher-kim',
    leaderUid: 'demo-student-26001',
    clubName: '밴드부',
    targetGrades: [1, 2, 3],
    description: '교내 공연을 준비하며 밴드 합주와 작곡 활동을 함께 합니다.',
    room: '음악실',
    maxMembers: 12,
    isInterviewSelection: false,
    memberCount: 5,
    randomDrawnRounds: [],
    createdByUid: 'demo-teacher-kim',
  },
  {
    id: '2',
    teacherUid: 'demo-teacher-park',
    leaderUid: 'demo-student-26002',
    clubName: '축구부',
    targetGrades: [1, 2],
    description: '주 2회 훈련과 교내 리그를 통해 팀워크를 기릅니다.',
    room: '운동장',
    maxMembers: 18,
    isInterviewSelection: false,
    memberCount: 14,
    randomDrawnRounds: [],
    createdByUid: 'demo-teacher-park',
  },
  {
    id: '3',
    teacherUid: 'demo-teacher-lee',
    leaderUid: 'demo-student-26003',
    clubName: '방송부',
    targetGrades: [1, 2, 3],
    description: '학교 행사 방송 송출과 콘텐츠 제작을 담당합니다.',
    room: '방송실',
    maxMembers: 8,
    isInterviewSelection: true,
    memberCount: 6,
    randomDrawnRounds: [],
    createdByUid: 'demo-teacher-lee',
  },
  {
    id: '4',
    teacherUid: 'demo-teacher-choi',
    leaderUid: 'demo-student-26004',
    clubName: '과학탐구부',
    targetGrades: [2, 3],
    description: '탐구 프로젝트를 설계하고 과학전람회 출품을 준비합니다.',
    room: '과학실',
    maxMembers: 10,
    isInterviewSelection: false,
    memberCount: 3,
    randomDrawnRounds: [],
    createdByUid: 'demo-teacher-choi',
  },
  {
    id: '5',
    teacherUid: 'demo-teacher-jung',
    leaderUid: 'demo-student-26005',
    clubName: '미술부',
    targetGrades: [1, 2, 3],
    description: '드로잉, 수채화, 포스터 제작 등 다양한 미술 활동을 진행합니다.',
    room: '미술실',
    maxMembers: 10,
    isInterviewSelection: false,
    memberCount: 10,
    randomDrawnRounds: [],
    createdByUid: 'demo-teacher-jung',
  },
]

export const mockStudents = {
  '1': [
    { id: 'st1', grade: '3', classNum: '2', number: '15', name: '김민준', gender: '남', notes: '' },
    { id: 'st2', grade: '3', classNum: '2', number: '8', name: '이서연', gender: '여', notes: '리듬 기타 지원' },
    { id: 'st3', grade: '4', classNum: '1', number: '22', name: '박지호', gender: '남', notes: '드럼 지원' },
  ],
  '2': [
    { id: 'st4', grade: '2', classNum: '3', number: '11', name: '최수아', gender: '여', notes: '' },
    { id: 'st5', grade: '1', classNum: '5', number: '7', name: '정예준', gender: '남', notes: '주전 경험 있음' },
  ],
}
